spring.application.name=careerinde-app

spring.datasource.url=jdbc:postgresql://localhost:5433/careerinde
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

openai.api.key=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